/**
 * Nationalities dataset for Owner KYC.
 * Based on ISO 3166-1 alpha-2 country codes with demonyms.
 * Reuses country dataset concept from location system (lib/location/countries, geo.data).
 */

export interface NationalityOption {
  code: string;
  countryCode: string;
  label: string;
  demonym: string;
}

function build(
  code: string,
  name: string,
  demonym?: string
): NationalityOption {
  return {
    code,
    countryCode: code,
    label: name,
    demonym: demonym ?? `${name} national`,
  };
}

/** All countries/territories with demonyms. ISO 3166-1 alpha-2. */
export const NATIONALITIES: NationalityOption[] = [
  build("AF", "Afghanistan", "Afghan"),
  build("AL", "Albania", "Albanian"),
  build("DZ", "Algeria", "Algerian"),
  build("AD", "Andorra", "Andorran"),
  build("AO", "Angola", "Angolan"),
  build("AG", "Antigua and Barbuda", "Antiguan"),
  build("AR", "Argentina", "Argentine"),
  build("AM", "Armenia", "Armenian"),
  build("AU", "Australia", "Australian"),
  build("AT", "Austria", "Austrian"),
  build("AZ", "Azerbaijan", "Azerbaijani"),
  build("BS", "Bahamas", "Bahamian"),
  build("BH", "Bahrain", "Bahraini"),
  build("BD", "Bangladesh", "Bangladeshi"),
  build("BB", "Barbados", "Barbadian"),
  build("BY", "Belarus", "Belarusian"),
  build("BE", "Belgium", "Belgian"),
  build("BZ", "Belize", "Belizean"),
  build("BJ", "Benin", "Beninese"),
  build("BT", "Bhutan", "Bhutanese"),
  build("BO", "Bolivia", "Bolivian"),
  build("BA", "Bosnia and Herzegovina", "Bosnian"),
  build("BW", "Botswana", "Motswana"),
  build("BR", "Brazil", "Brazilian"),
  build("BN", "Brunei", "Bruneian"),
  build("BG", "Bulgaria", "Bulgarian"),
  build("BF", "Burkina Faso", "Burkinabe"),
  build("BI", "Burundi", "Burundian"),
  build("KH", "Cambodia", "Cambodian"),
  build("CM", "Cameroon", "Cameroonian"),
  build("CA", "Canada", "Canadian"),
  build("CV", "Cape Verde", "Cape Verdean"),
  build("CF", "Central African Republic", "Central African"),
  build("TD", "Chad", "Chadian"),
  build("CL", "Chile", "Chilean"),
  build("CN", "China", "Chinese"),
  build("CO", "Colombia", "Colombian"),
  build("KM", "Comoros", "Comoran"),
  build("CG", "Congo", "Congolese"),
  build("CD", "Democratic Republic of the Congo", "Congolese"),
  build("CR", "Costa Rica", "Costa Rican"),
  build("HR", "Croatia", "Croatian"),
  build("CU", "Cuba", "Cuban"),
  build("CY", "Cyprus", "Cypriot"),
  build("CZ", "Czech Republic", "Czech"),
  build("DK", "Denmark", "Danish"),
  build("DJ", "Djibouti", "Djiboutian"),
  build("DM", "Dominica", "Dominican"),
  build("DO", "Dominican Republic", "Dominican"),
  build("EC", "Ecuador", "Ecuadorean"),
  build("EG", "Egypt", "Egyptian"),
  build("SV", "El Salvador", "Salvadorean"),
  build("GQ", "Equatorial Guinea", "Equatorial Guinean"),
  build("ER", "Eritrea", "Eritrean"),
  build("EE", "Estonia", "Estonian"),
  build("SZ", "Eswatini", "Swazi"),
  build("ET", "Ethiopia", "Ethiopian"),
  build("FJ", "Fiji", "Fijian"),
  build("FI", "Finland", "Finnish"),
  build("FR", "France", "French"),
  build("GA", "Gabon", "Gabonese"),
  build("GM", "Gambia", "Gambian"),
  build("GE", "Georgia", "Georgian"),
  build("DE", "Germany", "German"),
  build("GH", "Ghana", "Ghanaian"),
  build("GR", "Greece", "Greek"),
  build("GD", "Grenada", "Grenadian"),
  build("GT", "Guatemala", "Guatemalan"),
  build("GN", "Guinea", "Guinean"),
  build("GW", "Guinea-Bissau", "Bissau-Guinean"),
  build("GY", "Guyana", "Guyanese"),
  build("HT", "Haiti", "Haitian"),
  build("HN", "Honduras", "Honduran"),
  build("HU", "Hungary", "Hungarian"),
  build("IS", "Iceland", "Icelandic"),
  build("IN", "India", "Indian"),
  build("ID", "Indonesia", "Indonesian"),
  build("IR", "Iran", "Iranian"),
  build("IQ", "Iraq", "Iraqi"),
  build("IE", "Ireland", "Irish"),
  build("IL", "Israel", "Israeli"),
  build("IT", "Italy", "Italian"),
  build("CI", "Ivory Coast", "Ivorian"),
  build("JM", "Jamaica", "Jamaican"),
  build("JP", "Japan", "Japanese"),
  build("JO", "Jordan", "Jordanian"),
  build("KZ", "Kazakhstan", "Kazakhstani"),
  build("KE", "Kenya", "Kenyan"),
  build("KI", "Kiribati", "I-Kiribati"),
  build("KP", "North Korea", "North Korean"),
  build("KR", "South Korea", "South Korean"),
  build("KW", "Kuwait", "Kuwaiti"),
  build("KG", "Kyrgyzstan", "Kyrgyzstani"),
  build("LA", "Laos", "Lao"),
  build("LV", "Latvia", "Latvian"),
  build("LB", "Lebanon", "Lebanese"),
  build("LS", "Lesotho", "Basotho"),
  build("LR", "Liberia", "Liberian"),
  build("LY", "Libya", "Libyan"),
  build("LI", "Liechtenstein", "Liechtensteiner"),
  build("LT", "Lithuania", "Lithuanian"),
  build("LU", "Luxembourg", "Luxembourgish"),
  build("MG", "Madagascar", "Malagasy"),
  build("MW", "Malawi", "Malawian"),
  build("MY", "Malaysia", "Malaysian"),
  build("MV", "Maldives", "Maldivian"),
  build("ML", "Mali", "Malian"),
  build("MT", "Malta", "Maltese"),
  build("MH", "Marshall Islands", "Marshallese"),
  build("MR", "Mauritania", "Mauritanian"),
  build("MU", "Mauritius", "Mauritian"),
  build("MX", "Mexico", "Mexican"),
  build("FM", "Micronesia", "Micronesian"),
  build("MD", "Moldova", "Moldovan"),
  build("MC", "Monaco", "Monegasque"),
  build("MN", "Mongolia", "Mongolian"),
  build("ME", "Montenegro", "Montenegrin"),
  build("MA", "Morocco", "Moroccan"),
  build("MZ", "Mozambique", "Mozambican"),
  build("MM", "Myanmar", "Burmese"),
  build("NA", "Namibia", "Namibian"),
  build("NR", "Nauru", "Nauruan"),
  build("NP", "Nepal", "Nepalese"),
  build("NL", "Netherlands", "Dutch"),
  build("NZ", "New Zealand", "New Zealander"),
  build("NI", "Nicaragua", "Nicaraguan"),
  build("NE", "Niger", "Nigerien"),
  build("NG", "Nigeria", "Nigerian"),
  build("MK", "North Macedonia", "Macedonian"),
  build("NO", "Norway", "Norwegian"),
  build("OM", "Oman", "Omani"),
  build("PK", "Pakistan", "Pakistani"),
  build("PW", "Palau", "Palauan"),
  build("PS", "Palestine", "Palestinian"),
  build("PA", "Panama", "Panamanian"),
  build("PG", "Papua New Guinea", "Papua New Guinean"),
  build("PY", "Paraguay", "Paraguayan"),
  build("PE", "Peru", "Peruvian"),
  build("PH", "Philippines", "Filipino"),
  build("PL", "Poland", "Polish"),
  build("PT", "Portugal", "Portuguese"),
  build("QA", "Qatar", "Qatari"),
  build("RO", "Romania", "Romanian"),
  build("RU", "Russia", "Russian"),
  build("RW", "Rwanda", "Rwandan"),
  build("KN", "Saint Kitts and Nevis", "Kittitian"),
  build("LC", "Saint Lucia", "Saint Lucian"),
  build("VC", "Saint Vincent and the Grenadines", "Vincentian"),
  build("WS", "Samoa", "Samoan"),
  build("SM", "San Marino", "Sammarinese"),
  build("ST", "Sao Tome and Principe", "Sao Tomean"),
  build("SA", "Saudi Arabia", "Saudi"),
  build("SN", "Senegal", "Senegalese"),
  build("RS", "Serbia", "Serbian"),
  build("SC", "Seychelles", "Seychellois"),
  build("SL", "Sierra Leone", "Sierra Leonean"),
  build("SG", "Singapore", "Singaporean"),
  build("SK", "Slovakia", "Slovak"),
  build("SI", "Slovenia", "Slovenian"),
  build("SB", "Solomon Islands", "Solomon Islander"),
  build("SO", "Somalia", "Somali"),
  build("ZA", "South Africa", "South African"),
  build("SS", "South Sudan", "South Sudanese"),
  build("ES", "Spain", "Spanish"),
  build("LK", "Sri Lanka", "Sri Lankan"),
  build("SD", "Sudan", "Sudanese"),
  build("SR", "Suriname", "Surinamese"),
  build("SE", "Sweden", "Swedish"),
  build("CH", "Switzerland", "Swiss"),
  build("SY", "Syria", "Syrian"),
  build("TW", "Taiwan", "Taiwanese"),
  build("TJ", "Tajikistan", "Tajikistani"),
  build("TZ", "Tanzania", "Tanzanian"),
  build("TH", "Thailand", "Thai"),
  build("TL", "Timor-Leste", "Timorese"),
  build("TG", "Togo", "Togolese"),
  build("TO", "Tonga", "Tongan"),
  build("TT", "Trinidad and Tobago", "Trinidadian"),
  build("TN", "Tunisia", "Tunisian"),
  build("TR", "Turkey", "Turkish"),
  build("TM", "Turkmenistan", "Turkmen"),
  build("TV", "Tuvalu", "Tuvaluan"),
  build("UG", "Uganda", "Ugandan"),
  build("UA", "Ukraine", "Ukrainian"),
  build("AE", "United Arab Emirates", "Emirati"),
  build("GB", "United Kingdom", "British"),
  build("US", "United States", "American"),
  build("UY", "Uruguay", "Uruguayan"),
  build("UZ", "Uzbekistan", "Uzbekistani"),
  build("VU", "Vanuatu", "Ni-Vanuatu"),
  build("VA", "Vatican City", "Vatican"),
  build("VE", "Venezuela", "Venezuelan"),
  build("VN", "Vietnam", "Vietnamese"),
  build("YE", "Yemen", "Yemeni"),
  build("ZM", "Zambia", "Zambian"),
  build("ZW", "Zimbabwe", "Zimbabwean"),
  // Territories and extended
  build("AW", "Aruba", "Aruban"),
  build("AI", "Anguilla", "Anguillian"),
  build("BM", "Bermuda", "Bermudian"),
  build("KY", "Cayman Islands", "Caymanian"),
  build("FK", "Falkland Islands", "Falkland Islander"),
  build("GI", "Gibraltar", "Gibraltarian"),
  build("HK", "Hong Kong", "Hong Konger"),
  build("MO", "Macau", "Macanese"),
  build("PR", "Puerto Rico", "Puerto Rican"),
  build("RE", "Reunion", "Reunionese"),
  build("BL", "Saint Barthelemy", "Barthélemois"),
  build("MF", "Saint Martin", "Saint-Martinoise"),
  build("SH", "Saint Helena", "Saint Helenian"),
  build("SX", "Sint Maarten", "Sint Maarten"),
  build("TC", "Turks and Caicos Islands", "Turks and Caicos Islander"),
  build("VI", "U.S. Virgin Islands", "U.S. Virgin Islander"),
  build("WF", "Wallis and Futuna", "Wallisian"),
];

/** Get nationality by ISO country code. */
export function getNationalityByCode(code: string): NationalityOption | undefined {
  const c = String(code || "").trim().toUpperCase();
  if (!c) return undefined;
  return NATIONALITIES.find((n) => n.countryCode === c || n.code === c);
}

/** Get nationality by demonym (e.g. "Bangladeshi"). */
export function getNationalityByDemonym(demonym: string): NationalityOption | undefined {
  const d = String(demonym || "").trim().toLowerCase();
  if (!d) return undefined;
  return NATIONALITIES.find((n) => n.demonym.toLowerCase() === d);
}

/** Get nationality by country name. */
export function getNationalityByLabel(label: string): NationalityOption | undefined {
  const l = String(label || "").trim().toLowerCase();
  if (!l) return undefined;
  return NATIONALITIES.find(
    (n) => n.label.toLowerCase() === l || n.demonym.toLowerCase() === l
  );
}
