\
param(
  [Parameter(Mandatory=$true)][string]$Repo,
  [Parameter(Mandatory=$true)][string]$Version,
  [Parameter(Mandatory=$true)][string]$OutZip,
  [Parameter(Mandatory=$true)][string]$RootDir,
  [Parameter(Mandatory=$true)][string[]]$Files
)

$ErrorActionPreference = "Stop"

$tmp = Join-Path $env:TEMP ("bpa_patch_" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null

foreach ($f in $Files) {
  $src = Join-Path $RootDir $f
  if (!(Test-Path $src)) { throw "Missing file: $f" }

  $dest = Join-Path $tmp $f
  $destDir = Split-Path $dest -Parent
  New-Item -ItemType Directory -Path $destDir -Force | Out-Null
  Copy-Item $src $dest -Force
}

$patchNotes = @"
# PATCH NOTES

## Repo
$Repo

## Version
$Version

## Summary
- Update-only patch generated by script.

## Changed Files
$(($Files | ForEach-Object { "- " + $_ }) -join "`n")
"@
Set-Content -Path (Join-Path $tmp "PATCH_NOTES.md") -Value $patchNotes -Encoding UTF8

if (Test-Path $OutZip) { Remove-Item $OutZip -Force }
Compress-Archive -Path (Join-Path $tmp "*") -DestinationPath $OutZip

Remove-Item $tmp -Recurse -Force
Write-Host "✅ Patch ZIP created: $OutZip"
