#!/usr/bin/env bash
set -euo pipefail

REPO="${1:?repo required}"
VERSION="${2:?version required}"
OUTZIP="${3:?out zip required}"
ROOTDIR="${4:?root dir required}"
shift 4
FILES=("$@")

TMP="$(mktemp -d)"
cleanup(){ rm -rf "$TMP"; }
trap cleanup EXIT

for f in "${FILES[@]}"; do
  src="$ROOTDIR/$f"
  if [ ! -f "$src" ]; then
    echo "Missing file: $f" >&2
    exit 1
  fi
  mkdir -p "$TMP/$(dirname "$f")"
  cp "$src" "$TMP/$f"
done

{
  echo "# PATCH NOTES"
  echo
  echo "## Repo"
  echo "$REPO"
  echo
  echo "## Version"
  echo "$VERSION"
  echo
  echo "## Summary"
  echo "- Update-only patch generated by script."
  echo
  echo "## Changed Files"
  for f in "${FILES[@]}"; do echo "- $f"; done
} > "$TMP/PATCH_NOTES.md"

rm -f "$OUTZIP"
(cd "$TMP" && zip -r "$OUTZIP" . >/dev/null)
echo "✅ Patch ZIP created: $OUTZIP"
